add feature Cancelamento de Pedido
BrenoCinUfpe/ESS-E-commerce-Backend pull request #8
Opened 2024-05-29 02:42 UTC by gabrielapinheiroc

2024-05-29 02:57 UTC, BrenoRev requested changes
Há muitos commits para uma PR com 1 arquivo de 40 linhas, mergea os commits em algo mais unificado deixando claro o propósito do commit

2024-05-29 02:57 UTC, BrenoRev commented on features/CancelamentoDePedido.feature
> +<<<<<<< HEAD
Está com conflito de branch

2024-05-29 02:57 UTC, BrenoRev commented on features/CancelamentoDePedido.feature
> +>>>>>>> dev
Conflito de branch

2024-06-01 21:36 UTC, BrenoCinUfpe approved these changes

2024-06-01 21:37 UTC, BrenoRev approved these changes

2024-06-01 21:38 UTC, merged